/**
 * Project-owned additions to the generated Worker env.
 *
 * `worker-configuration.d.ts` is regenerated by `npm run cf-typegen` and
 * only knows about bindings declared in `wrangler.jsonc`. Secrets are set
 * out-of-band (`wrangler secret put` / `.dev.vars`), so they're declared
 * here instead — this file is never overwritten by codegen.
 */

interface __AnalyticsSecrets {
  /**
   * Bearer token for the read-only `/ext/v1/*` API consumed by external
   * clients (the TAP miniapp dashboard).
   *
   * When unset, `/ext/v1/*` returns 503 and stays completely closed —
   * absence of a token is never treated as "no auth required".
   */
  ANALYTICS_API_TOKEN?: string
}

declare namespace Cloudflare {
  interface Env extends __AnalyticsSecrets {}
}

interface Env extends __AnalyticsSecrets {}
