/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CollectRouteImport } from './routes/collect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSitesRouteImport } from './routes/api/sites'
import { Route as ApiSitesSiteIdRouteImport } from './routes/api/sites.$siteId'
import { Route as ApiSitesSiteIdTimeseriesRouteImport } from './routes/api/sites.$siteId.timeseries'
import { Route as ApiSitesSiteIdSummaryRouteImport } from './routes/api/sites.$siteId.summary'
import { Route as ApiSitesSiteIdSourcesRouteImport } from './routes/api/sites.$siteId.sources'
import { Route as ApiSitesSiteIdPagesRouteImport } from './routes/api/sites.$siteId.pages'
import { Route as ApiSitesSiteIdLocationsRouteImport } from './routes/api/sites.$siteId.locations'
import { Route as ApiSitesSiteIdDevicesRouteImport } from './routes/api/sites.$siteId.devices'
import { Route as ApiSitesSiteIdActivityRouteImport } from './routes/api/sites.$siteId.activity'
import { Route as ApiSitesSiteIdRealtimeWsRouteImport } from './routes/api/sites.$siteId.realtime.ws'

const CollectRoute = CollectRouteImport.update({
  id: '/collect',
  path: '/collect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitesRoute = ApiSitesRouteImport.update({
  id: '/api/sites',
  path: '/api/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitesSiteIdRoute = ApiSitesSiteIdRouteImport.update({
  id: '/$siteId',
  path: '/$siteId',
  getParentRoute: () => ApiSitesRoute,
} as any)
const ApiSitesSiteIdTimeseriesRoute =
  ApiSitesSiteIdTimeseriesRouteImport.update({
    id: '/timeseries',
    path: '/timeseries',
    getParentRoute: () => ApiSitesSiteIdRoute,
  } as any)
const ApiSitesSiteIdSummaryRoute = ApiSitesSiteIdSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => ApiSitesSiteIdRoute,
} as any)
const ApiSitesSiteIdSourcesRoute = ApiSitesSiteIdSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => ApiSitesSiteIdRoute,
} as any)
const ApiSitesSiteIdPagesRoute = ApiSitesSiteIdPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => ApiSitesSiteIdRoute,
} as any)
const ApiSitesSiteIdLocationsRoute = ApiSitesSiteIdLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => ApiSitesSiteIdRoute,
} as any)
const ApiSitesSiteIdDevicesRoute = ApiSitesSiteIdDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => ApiSitesSiteIdRoute,
} as any)
const ApiSitesSiteIdActivityRoute = ApiSitesSiteIdActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ApiSitesSiteIdRoute,
} as any)
const ApiSitesSiteIdRealtimeWsRoute =
  ApiSitesSiteIdRealtimeWsRouteImport.update({
    id: '/realtime/ws',
    path: '/realtime/ws',
    getParentRoute: () => ApiSitesSiteIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collect': typeof CollectRoute
  '/api/sites': typeof ApiSitesRouteWithChildren
  '/api/sites/$siteId': typeof ApiSitesSiteIdRouteWithChildren
  '/api/sites/$siteId/activity': typeof ApiSitesSiteIdActivityRoute
  '/api/sites/$siteId/devices': typeof ApiSitesSiteIdDevicesRoute
  '/api/sites/$siteId/locations': typeof ApiSitesSiteIdLocationsRoute
  '/api/sites/$siteId/pages': typeof ApiSitesSiteIdPagesRoute
  '/api/sites/$siteId/sources': typeof ApiSitesSiteIdSourcesRoute
  '/api/sites/$siteId/summary': typeof ApiSitesSiteIdSummaryRoute
  '/api/sites/$siteId/timeseries': typeof ApiSitesSiteIdTimeseriesRoute
  '/api/sites/$siteId/realtime/ws': typeof ApiSitesSiteIdRealtimeWsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collect': typeof CollectRoute
  '/api/sites': typeof ApiSitesRouteWithChildren
  '/api/sites/$siteId': typeof ApiSitesSiteIdRouteWithChildren
  '/api/sites/$siteId/activity': typeof ApiSitesSiteIdActivityRoute
  '/api/sites/$siteId/devices': typeof ApiSitesSiteIdDevicesRoute
  '/api/sites/$siteId/locations': typeof ApiSitesSiteIdLocationsRoute
  '/api/sites/$siteId/pages': typeof ApiSitesSiteIdPagesRoute
  '/api/sites/$siteId/sources': typeof ApiSitesSiteIdSourcesRoute
  '/api/sites/$siteId/summary': typeof ApiSitesSiteIdSummaryRoute
  '/api/sites/$siteId/timeseries': typeof ApiSitesSiteIdTimeseriesRoute
  '/api/sites/$siteId/realtime/ws': typeof ApiSitesSiteIdRealtimeWsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collect': typeof CollectRoute
  '/api/sites': typeof ApiSitesRouteWithChildren
  '/api/sites/$siteId': typeof ApiSitesSiteIdRouteWithChildren
  '/api/sites/$siteId/activity': typeof ApiSitesSiteIdActivityRoute
  '/api/sites/$siteId/devices': typeof ApiSitesSiteIdDevicesRoute
  '/api/sites/$siteId/locations': typeof ApiSitesSiteIdLocationsRoute
  '/api/sites/$siteId/pages': typeof ApiSitesSiteIdPagesRoute
  '/api/sites/$siteId/sources': typeof ApiSitesSiteIdSourcesRoute
  '/api/sites/$siteId/summary': typeof ApiSitesSiteIdSummaryRoute
  '/api/sites/$siteId/timeseries': typeof ApiSitesSiteIdTimeseriesRoute
  '/api/sites/$siteId/realtime/ws': typeof ApiSitesSiteIdRealtimeWsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collect'
    | '/api/sites'
    | '/api/sites/$siteId'
    | '/api/sites/$siteId/activity'
    | '/api/sites/$siteId/devices'
    | '/api/sites/$siteId/locations'
    | '/api/sites/$siteId/pages'
    | '/api/sites/$siteId/sources'
    | '/api/sites/$siteId/summary'
    | '/api/sites/$siteId/timeseries'
    | '/api/sites/$siteId/realtime/ws'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collect'
    | '/api/sites'
    | '/api/sites/$siteId'
    | '/api/sites/$siteId/activity'
    | '/api/sites/$siteId/devices'
    | '/api/sites/$siteId/locations'
    | '/api/sites/$siteId/pages'
    | '/api/sites/$siteId/sources'
    | '/api/sites/$siteId/summary'
    | '/api/sites/$siteId/timeseries'
    | '/api/sites/$siteId/realtime/ws'
  id:
    | '__root__'
    | '/'
    | '/collect'
    | '/api/sites'
    | '/api/sites/$siteId'
    | '/api/sites/$siteId/activity'
    | '/api/sites/$siteId/devices'
    | '/api/sites/$siteId/locations'
    | '/api/sites/$siteId/pages'
    | '/api/sites/$siteId/sources'
    | '/api/sites/$siteId/summary'
    | '/api/sites/$siteId/timeseries'
    | '/api/sites/$siteId/realtime/ws'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectRoute: typeof CollectRoute
  ApiSitesRoute: typeof ApiSitesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/collect': {
      id: '/collect'
      path: '/collect'
      fullPath: '/collect'
      preLoaderRoute: typeof CollectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sites': {
      id: '/api/sites'
      path: '/api/sites'
      fullPath: '/api/sites'
      preLoaderRoute: typeof ApiSitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sites/$siteId': {
      id: '/api/sites/$siteId'
      path: '/$siteId'
      fullPath: '/api/sites/$siteId'
      preLoaderRoute: typeof ApiSitesSiteIdRouteImport
      parentRoute: typeof ApiSitesRoute
    }
    '/api/sites/$siteId/timeseries': {
      id: '/api/sites/$siteId/timeseries'
      path: '/timeseries'
      fullPath: '/api/sites/$siteId/timeseries'
      preLoaderRoute: typeof ApiSitesSiteIdTimeseriesRouteImport
      parentRoute: typeof ApiSitesSiteIdRoute
    }
    '/api/sites/$siteId/summary': {
      id: '/api/sites/$siteId/summary'
      path: '/summary'
      fullPath: '/api/sites/$siteId/summary'
      preLoaderRoute: typeof ApiSitesSiteIdSummaryRouteImport
      parentRoute: typeof ApiSitesSiteIdRoute
    }
    '/api/sites/$siteId/sources': {
      id: '/api/sites/$siteId/sources'
      path: '/sources'
      fullPath: '/api/sites/$siteId/sources'
      preLoaderRoute: typeof ApiSitesSiteIdSourcesRouteImport
      parentRoute: typeof ApiSitesSiteIdRoute
    }
    '/api/sites/$siteId/pages': {
      id: '/api/sites/$siteId/pages'
      path: '/pages'
      fullPath: '/api/sites/$siteId/pages'
      preLoaderRoute: typeof ApiSitesSiteIdPagesRouteImport
      parentRoute: typeof ApiSitesSiteIdRoute
    }
    '/api/sites/$siteId/locations': {
      id: '/api/sites/$siteId/locations'
      path: '/locations'
      fullPath: '/api/sites/$siteId/locations'
      preLoaderRoute: typeof ApiSitesSiteIdLocationsRouteImport
      parentRoute: typeof ApiSitesSiteIdRoute
    }
    '/api/sites/$siteId/devices': {
      id: '/api/sites/$siteId/devices'
      path: '/devices'
      fullPath: '/api/sites/$siteId/devices'
      preLoaderRoute: typeof ApiSitesSiteIdDevicesRouteImport
      parentRoute: typeof ApiSitesSiteIdRoute
    }
    '/api/sites/$siteId/activity': {
      id: '/api/sites/$siteId/activity'
      path: '/activity'
      fullPath: '/api/sites/$siteId/activity'
      preLoaderRoute: typeof ApiSitesSiteIdActivityRouteImport
      parentRoute: typeof ApiSitesSiteIdRoute
    }
    '/api/sites/$siteId/realtime/ws': {
      id: '/api/sites/$siteId/realtime/ws'
      path: '/realtime/ws'
      fullPath: '/api/sites/$siteId/realtime/ws'
      preLoaderRoute: typeof ApiSitesSiteIdRealtimeWsRouteImport
      parentRoute: typeof ApiSitesSiteIdRoute
    }
  }
}

interface ApiSitesSiteIdRouteChildren {
  ApiSitesSiteIdActivityRoute: typeof ApiSitesSiteIdActivityRoute
  ApiSitesSiteIdDevicesRoute: typeof ApiSitesSiteIdDevicesRoute
  ApiSitesSiteIdLocationsRoute: typeof ApiSitesSiteIdLocationsRoute
  ApiSitesSiteIdPagesRoute: typeof ApiSitesSiteIdPagesRoute
  ApiSitesSiteIdSourcesRoute: typeof ApiSitesSiteIdSourcesRoute
  ApiSitesSiteIdSummaryRoute: typeof ApiSitesSiteIdSummaryRoute
  ApiSitesSiteIdTimeseriesRoute: typeof ApiSitesSiteIdTimeseriesRoute
  ApiSitesSiteIdRealtimeWsRoute: typeof ApiSitesSiteIdRealtimeWsRoute
}

const ApiSitesSiteIdRouteChildren: ApiSitesSiteIdRouteChildren = {
  ApiSitesSiteIdActivityRoute: ApiSitesSiteIdActivityRoute,
  ApiSitesSiteIdDevicesRoute: ApiSitesSiteIdDevicesRoute,
  ApiSitesSiteIdLocationsRoute: ApiSitesSiteIdLocationsRoute,
  ApiSitesSiteIdPagesRoute: ApiSitesSiteIdPagesRoute,
  ApiSitesSiteIdSourcesRoute: ApiSitesSiteIdSourcesRoute,
  ApiSitesSiteIdSummaryRoute: ApiSitesSiteIdSummaryRoute,
  ApiSitesSiteIdTimeseriesRoute: ApiSitesSiteIdTimeseriesRoute,
  ApiSitesSiteIdRealtimeWsRoute: ApiSitesSiteIdRealtimeWsRoute,
}

const ApiSitesSiteIdRouteWithChildren = ApiSitesSiteIdRoute._addFileChildren(
  ApiSitesSiteIdRouteChildren,
)

interface ApiSitesRouteChildren {
  ApiSitesSiteIdRoute: typeof ApiSitesSiteIdRouteWithChildren
}

const ApiSitesRouteChildren: ApiSitesRouteChildren = {
  ApiSitesSiteIdRoute: ApiSitesSiteIdRouteWithChildren,
}

const ApiSitesRouteWithChildren = ApiSitesRoute._addFileChildren(
  ApiSitesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectRoute: CollectRoute,
  ApiSitesRoute: ApiSitesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
